Interface avec le simulateur
eirbot/eirbot2020-2A pull request #14
Opened 2019-10-23 18:55 UTC by polyedre

J'essaie d'adapter mon code pour l'interface du simulateur qu'on a définie dans https://github.com/eirbot/eirbot2020-2A/issues/12.

Il me manque encore l'implémentation des classes Output et Input. Vous avez sûrement quelque chose qui ferait le taf dans vos archives ?

Je suis ouverts aux remarques

2019-10-25 08:06 UTC, astralien3000 commented
J'essaie de regarder ça ce weekend !

2019-10-26 07:28 UTC, astralien3000 commented
C'est normal que ça compile pas ?

```
src/main.cpp:457:9: error: reference to 'move' is ambiguous
```

2019-10-26 07:32 UTC, astralien3000 commented
Output et Input n'ont pas d'implémentation. Ce sont des API, elles ne servent à rien d'autre que nous donner les noms des méthodes qu'on devrait utiliser.

2019-10-26 07:36 UTC, astralien3000 commented on robot_2A/src/encoder.hpp
> +  Encoder(Input encoder);
C'est le Input dont il manque l'implémentation ? Elle ne doit pas être utilisée de cette façon.
Ça n'a pas de sens de construire un Encoder à partir d'un encoder.
Laisse le timer en constructeur comme tu a l'habitude.

2019-10-26 07:40 UTC, astralien3000 requested changes

2019-10-26 07:40 UTC, astralien3000 commented on robot_2A/src/motor_controller.cpp
> +MotorController::MotorController(Output motor_pwm, Input encoder) {
Bon, ça pourrait marcher si Output et Input étaient des classes polymorphiques, ce qu'elles peuvent être. Et surtout si c'était des références et pas des objets passés par copie. Mais les classes polymorphiques c'est le mal (sur microcontrôleur). Met des références de Motor et Encoder à la place.

2019-10-27 08:19 UTC, polyedre commented on robot_2A/src/encoder.hpp
> +  Encoder(Input encoder);
Pour les encodeurs c'est un peu compliqué, je peux l'implémenter avec TIM3 et TIM4 (je sais pas vraiment ce que ça représente). Toujours est-il qu'il me faut un moyen dans les arguments du constructeur de distinguer les deux, et il faut que ce soit valide pour l'interface du Simulateur, donc je vois pas vraiment comment faire

2019-10-27 08:22 UTC, polyedre commented
> C'est normal que ça compile pas chez moi ?
> 
> ```
> src/main.cpp:457:9: error: reference to 'move' is ambiguous
> ```
> 
> EDIT : version de compilateur ?

Je sais pas trop, j'utilise `platformio` pour compiler (paquet python installable via `pip`)

2019-10-27 08:23 UTC, polyedre commented on robot_2A/src/motor_controller.cpp
> +MotorController::MotorController(Output motor_pwm, Input encoder) {
Je voulais que ce soit cette classe qui instancie le moteur et l'encoder. Donc je ne voulais pas lui passer directement les objets :)

2019-10-27 11:55 UTC, astralien3000 commented on robot_2A/src/encoder.hpp
> +  Encoder(Input encoder);
```c++
Encoder(TIM_TypeDef* timer);
```

Pas besoin que ce soit valide pour le simulateur. Je s'occupe de la compatibilité.

2019-10-27 12:02 UTC, astralien3000 commented on robot_2A/src/motor_controller.cpp
> +MotorController::MotorController(Output motor_pwm, Input encoder) {
?? J'ai du mal à comprendre.
Si la classe instancie les objets, pourquoi lui donner en paramètres de constructeurs ?
Le encodeurs et moteurs sont déjà instanciés ailleurs dans l'espace global, pas besoin de les réinstancier, et surtout que pour les instancier ici il faut différencier les enc/mot gauche et droit dans le constructeur (TIM3/TIM4 et PWMx/PWMy), ça va pas être pratique.
Pour moi il faut juste dire à l'objet où trouver le moteur et l'encodeur, donc lui donner des références / pointeurs.

2019-10-27 14:53 UTC, astralien3000 commented
Pour qu'on sache bien de quoi on parle, je t'ai mis comment je vois les choses dans [une PR vers ta branche](https://github.com/polyedre/eirbot2020-2A/pull/1). Si tu accepte la proposition, tu peux merger dans ta branche, et cette PR sera automatiquement mise à jour.

2019-10-28 17:21 UTC, polyedre commented on robot_2A/src/motor_controller.cpp
> +MotorController::MotorController(Output motor_pwm, Input encoder) {
Ça marche ! Je vais faire ça

2019-10-28 22:46 UTC, astralien3000 commented
Il y a encore du travail sur cette PR ? Parce que pour moi c'est OK pour merger dans master.

2019-10-28 22:47 UTC, astralien3000 approved these changes

2019-10-29 00:21 UTC, Elioty reviewed
Bonne lecture 😄

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.cpp
> +GP2::GP2(AnalogIn *_input, float _distance_seuil) {
Pourquoi ne pas utiliser les constructeurs des membres ici plutôt que leur operator= ?

2019-10-29 00:21 UTC, Elioty commented on .gitignore
> +*~
Pas de saut de ligne à la fin du fichier, ce n'est pas très UNIX-compliant 😝

2019-10-29 00:21 UTC, Elioty commented on robot_2A/platformio.ini
> +monitor_speed = 115200
Pas de saut de ligne à la fin du fichier, ce n'est pas très UNIX-compliant 😝

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.cpp
> +int GP2::detected() { return input->read() * GP2_COEF > distance_seuil; }
Tu devrais appeler get_Distance ici plutôt que de refaire le calcul. Le compilateur se débrouillera très bien pour optimiser.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.cpp
> +float GP2::get_Distance() { return (input->read() * GP2_COEF); }
return is not a function. Ça me fait toujours bizarre perso les parenthèses sur un return mais c'est plus un avis personnel ça.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.cpp
> +void GP2::debug() { printf("GP2 : %f, %f", input->read(), get_Distance()); }
C'est voulu l'absence d'un \n à la fin de la chaine ?
Et ta lib ne supporte pas les opérateurs de flux avec un stdout ? Ça reste un choix discutable les fluxes, je vous laisse voir.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.hpp
> +  float distance_seuil;
seuil => threshold.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.hpp
> +  float real_distance;
Un membre en public ? Je ne l'ai d'ailleurs pas vu dans GP2.c !

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/GP2.cpp
> +int detected_all(GP2 gp2_list[], int gp2_nb) {
La signature ne colle pas avec celle dans le .h !

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/base.cpp
> +    *direction == 1 ? *direction = 0 : *direction = 1;
Une affection dans les deux résultats possibles d'une ternaire, c'est très moche.
Aussi, direction ne devrait-il pas plutôt utiliser un type énuméré ?
À défaut, la ligne peut simplement être ```*direction = !*direction```, pas besoin de condition !

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/base.cpp
> +    *consigne = abs(*consigne);
Tu as déjà vérifié que la valeur était négative, un ```*consigne = -*consigne``` sera plus efficace, si tu compiles en freestanding. En hosted, le compilateur doit déjà faire l'optimisation suscitée plutôt que de faire un appel de fonction qui refera le même if, mais les branches et appels de fonction ne sont pas ce qu'il y a de plus efficace, si ta puce dispose d'un cache et d'une prédication de branchement (qui peut se tromper, donc autant faire sans branche si possible, remarque qui tient pour la ternaire au dessus).
Autre problème, ça devrait être fabsf !!! Sauf si l'arrondi à l'entier induis par le cast implicite est voulu ?!

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/base.cpp
> +float max(float a, float b) { return (a < b) ? b : a; }
La libraire standard que tu as fournit printf mais fminf ou fmaxf ?
https://en.cppreference.com/w/c/numeric/math/fmin
https://en.cppreference.com/w/c/numeric/math/fmax

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/config.hpp
> +#define CENTER_WALL_POS (side == BLUE_RIGHT ? 1.5f : 0.5f)
Deux macros qui prennent des "arguments" par effet de bord, c'est un peu borderline. Je sais que ça simplifie beaucoup le code répétitif mais est-ce que ça a sa place dans un fichier nommé config.hpp ? Je fais personnellement ce genre de chose uniquement dans une fonction et j'undef la macro à la fin du bloc où je l'ai définie.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/encoder.cpp
> +
Les deux fonctions au dessus mériteraient de la factorisation.
Sinon, d'un point de vue fonctionnel, je n'ai pas lu la datasheet de la puce en question, mais ça serait certainement mieux de mettre le compteur à 0 avant de l'activer !
Aussi, je ne connais pas la lib HAL que tu utilises mais ça se passe comment si quelqu'un d'autre cherche à initialiser ces deux GPIO A et D même si ce n'est juste pour utiliser d'autres pins. Ils appelleront aussi HAL_GPIO_Init mais cela ne viendrait-il pas rincer la configuration qui est faite ici ?

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/encoder.cpp
> +int32_t Encoder::getDistance() {
La signature ne colle pas avec le .h, tu as mis void dans les arguments de l'autre côté.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/encoder.hpp
> +extern Encoder enc_r;
Ces deux variables sont déclarées ici mais ne sont pas définies dans encoder.c, est-ce normal ?

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/main.cpp
> +
Ça serait peut être mieux d'avoir un fichier data.c par exemple pour définir toutes les variables de ce genre, non ?
Pas relu le reste de ce fichier.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/motor.hpp
> +extern Motor mot_r;
Même remarque que pour les encodeurs.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/navigation/vecteur2D.cpp
> +}
Pas de saut de ligne à la fin.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.cpp
> +  if (abs(consigne - new_consigne) > 0.05f) {
fabsf parce que là, ça n'a pas vraiment pas de sens d'utiliser abs avec le test qu'il y a.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.cpp
> +  for (int i = tab_size; i > 0; i--) {
Alerte au buffer overflow !!! i devrait être initialisée à ```tab_size - 1``` !

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.cpp
> +  tab_shift(derivee_data, 3);
Une taille de tableau en dur ici ?

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.cpp
> +  if (abs(erreur) < erreurSeuil) {
fabsf.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.hpp
> +  short actionFinished;
bool.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.hpp
> +  void setCommande(float theta);
L'argument s'appelle v dans le .c.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/pid.hpp
> +  float commande_vitesse = 0;
C'est bien compilé en C++11 ou supérieur ?

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/position.hpp
> +        float get_theta();
À quoi servent les getters si les membres concernés sont publiques ?

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/position.hpp
> +        Encoder* encod_r;
Encodeurs publiques ? On peut avoir besoin de les changer à la volée ? 😝

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/position.cpp
> +float sg(float val) { return (val < 0.0f) ? -1.0f : 1.0f; }
=> ```copysignf(1.f, val)```
Et je n'ai pas vu la déclaration de cette fonction dans position.hpp et elle n'est pas utilisé dans ce fichier ?!

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/navigation/navigateur.cpp
> +  if ((abs(angle_relatif) < 0.3) || (abs(abs(angle_relatif) - PI) < 0.3)) {
fabsf et les deux 0.3 sont des double ici.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/navigation/navigateur.cpp
> +  if ((angle_relatif > PI - 0.7) || (angle_relatif < -PI + 0.7)) {
De même, les 0.7 sont double ici.

2019-10-29 00:21 UTC, Elioty commented on robot_2A/src/navigation/navigateur.cpp
> +  dist_cons = min(dist_cons, 0.2);
0.2 est double ici, pas cohérent avec l'affection trois lignes plus bas.

2019-10-29 07:46 UTC, astralien3000 commented on robot_2A/src/encoder.cpp
> +
La lib HAL utilisée ici est STM32Cube.
Pour le compteur, c'est pas important.
Et pour les GPIO, le mask de pins permet de choisir lesquelles seront affectées ou pas.

2019-10-29 07:49 UTC, astralien3000 commented on robot_2A/src/encoder.hpp
> +extern Encoder enc_r;
C'est moi qui ai ajouté ces globales.
Elles font partie de l'API Encoder comme discuté dans #12.
Je les ai pas définies parce qu'elles sont pas utilisées pour le moment.

2019-10-29 07:50 UTC, astralien3000 commented on robot_2A/src/motor.hpp
> +extern Motor mot_r;
Idem

2019-10-29 08:01 UTC, astralien3000 commented
@Elioty, tes remarques sont (bien sûr) importantes et à corriger. J'en ai aussi quelques unes d'autre en tête, et il y a aussi quelques fichier que j'ai pas voulu regarder (trop peur ! XD).
Mais j'aimerai corriger la structure du code avant de corriger les détails d'implémentation. Il y aura sûrement une partie des remarques qu'on peut faire qui seront obsolètes.

2019-10-29 23:30 UTC, Elioty commented on robot_2A/src/encoder.cpp
> +
Pour le compteur, c'est du détail effectivement, surtout si on a une procédure de recalage derrière avant le début du match.
Pour la fonction HAL_GPIO_Init, je vois, ça ne touche qu'à la configuration des pins renseignés dans le mask donc c'est OK !

2019-10-29 23:35 UTC, Elioty commented
@astralien3000 Je ne sais pas si tu as remarqué mais j'ai fait des remarques sur tous les fichiers... SAUF le main.c 😆 Pour l'architecture du code, je ne me suis pas fait de schéma pour voir comment tout cela couchait ensemble, j'ai juste lu le contenu de la PR de manière linéaire. D'ailleurs quelques schémas UML ne seraient pas de trop si tu veux bien poser ça au propre et pour en discuter plus facilement.

2019-10-29 23:43 UTC, Elioty commented
@polyedre n'aie pas peur, la première PR avec les bases de l'architecture est toujours un long débat (surtout si ça n'a pas déjà été discuté longuement) mais ça se passera mieux par la suite 😉

2019-10-30 06:48 UTC, astralien3000 commented
Comme dit sur #12 , je me réfère aux documents dans le dépôt [astralien3000/robot-control-tuto]().
C'est pas un UML, mais ça donne une bonne idée de l'archi vers laquelle je pousse : 
![archi](https://raw.githubusercontent.com/astralien3000/robot-control-tuto/master/2wheel/img/2Wheel_Trajectory_Control.png)

2019-11-30 15:09 UTC, closed without merging